### PR TITLE
Corrected makefile

### PR DESCRIPTION
**Pull request by omeh-a**
Added a missing `-I.` in the CFLAGS for DPDK. Without this, it fails to correctly find `lwipopts.h`.

### CODE REVIEW

**Comment by yasukata** [comment]
Thank you for your pull request.

Could you tell me the situation where your compiler failed to find ```lwipopts.h``` (i.e., the OS distribution and the commands you typed to build the program) so that I can reproduce the issue?

**Comment by omeh-a** [comment]
Hi there.

I have tested this on a few machines for experimentation at my work.

All four machines are Debian bullseye with various x86 configurations. Three of them use unstable and the other is stable.

Running `make` correctly prompts LWIP and DPDK to be downloaded and built, but it then fails due to a linker error when trying to link your `lwipopts.h`. The error is below:
```
gcc -O3 -pipe -Werror -Wall -Wunused-function -Wextra -include rte_config.h -march=native -I/home/mattr/Downloads/tinyhttpd-lwip-dpdk/dpdk/install/include -I/home/mattr/Downloads/tinyhttpd-lwip-dpdk/lwip/lwip-2.1.3/src/include -I/home/mattr/Downloads/tinyhttpd-lwip-dpdk/lwip/contrib-2.1.0 -I/home/mattr/Downloads/tinyhttpd-lwip-dpdk/lwip/contrib-2.1.0/ports/unix/port/include   -c -o main.o main.c
In file included from main.c:53:
/home/mattr/Downloads/tinyhttpd-lwip-dpdk/lwip/lwip-2.1.3/src/include/lwip/opt.h:51:10: fatal error: lwipopts.h: No such file or directory
51 | #include "lwipopts.h"
|          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: main.o] Error 1
```

Installing lwip as a system library does not fix this issue. It might be a Debian thing if this works on your system. The one line I have changed in the Makefile in this pull request explicitly includes it.

**Comment by yasukata** [comment]
Thank you for the information.

I could reproduce the issue on Debian, and I confirmed your change fixed it.

I would like to merge your change.

Before merging, could you update the following parts of your commit?
- the commit adds ```-I.``` to line 29 which is primarily for DPDK, therefore, could you add a new line ```CFLAGS += -I.``` just after line 15?
- the commit includes two binary files ```app``` and ```main.o``` which are not necessary for the source code repository, therefore, could you remove these two files from the commit?

Thank you for sending the patch.

**Comment by yasukata** [comment]
Please let me close this pull request since the fix is applied by https://github.com/yasukata/tinyhttpd-lwip-dpdk/pull/5.
Thank you for reporting this issue.

**Pull request closed without merging**
